try {
    undefined();
} catch (err) {
    console.log(err);
}